name: Verification Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck python3-pip
          pip3 install flake8 cpplint
      - name: Run static analysis
        run: bash scripts/run_static_analysis.sh

  unit-tests:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run unit tests
        run: python3 -m unittest discover -s ros2_ws/src/rover_autonomy/tests
